name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - run: mvn --batch-mode --update-snapshots package
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
      - name: jacoco-badge-generator
        uses: cicirello/jacoco-badge-generator@v2.8.1
